steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/web:latest
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/web:latest
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
  - run
  - deploy
  - web
  - --allow-unauthenticated
  - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/web:latest
  - --region=${_REGION}
images:
- ${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/web:latest
substitutions:
  _REGION: us-central1